// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayer.Entities.Concrete.Employee.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EemployeeFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCitizenshipNo")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCityOfRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCompanyDegreeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCompanyIdentityNo")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCompanySeniorityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCompanyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCountyOfRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EmployeeDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EmployeeDateOfStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeDayOffNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeDrivinLicenseClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeMaritalStatus")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeNumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("EmployeePartnerWorkingStatus")
                        .HasColumnType("int");

                    b.Property<string>("EmployeePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeUnionIdentityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeUnionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeWage")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeemployeeBirthplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
